### ISSUE TITLE
Add granting information (Förderkennzeichen)

### ISSUE THREAD

**Issue by mbdo** [mbdo/mbdo.github.io#2]
There's a fixed sentence by DFG that we need to include. Should be in the granting information at S

**Comment by Jinaz** [comment]
keywords: "Hinweis auf die DFG-Förderung (sog. „Funding Acknowledgement“)"

in our case:
Gefördert durch die Deutsche Forschungsgemeinschaft (DFG) - 505496753

funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation) - 505496753

**Comment by mbdo** [comment]
Please put that into the footer of the main page (go to mbo.github.io and grep for "TODO" to see what needs to be replaced)

**Comment by Jinaz** [comment]
footer updated in https://github.com/mbdo/mbdo.github.io/commit/abc510548b1ed642ff1a5ba779c1a5a17ef45454
