### ISSUE TITLE
Change header picutre for UR1

### ISSUE THREAD

**Issue by mbdo** [mbdo/mbdo.github.io#5]
Needs to become a picture that we have a license for

**Comment by mbdo** [comment]
Feel free to use something that is not the UR1 building.

**Comment by dvojtise** [comment]
Maybe the "moebius ring sculture" in front of the campus (but I'm not sure that there isn't license problem even if I take the picture myself ...) (cf. https://www.bing.com/images/search?q=univ+rennes+moebius&form=HDRSC3&first=1 )

**Comment by awortmann** [comment]
I'd like that. Could you take a photo in good conditions?
