### ISSUE TITLE
Replace TODO with link to gitlab in Navigation.yml

### ISSUE THREAD

**Issue by mbdo** [mbdo/mbdo.github.io#9]
- text: GitLab
  href: **TODO**
  new_window: true

(Landet alles bei Dir, weil Nico die Einladung zum Projekt noch nicht angenommen hat)

**Comment by frademacher** [comment]
After creation of the MBDO group at RWTH's GitLab, Nico and me recognized that it is not possible to make the group public without disclosing all stored information. We therefore propose to remove the GitLab link from the website for now and maybe later add a link to the source code on GitHub (which might be mirrored from the internal GitLab).
